name:                words
version:             0.1.0.0
github:              "dongarerahul/words"
license:             BSD3
author:              "Dongare Rahul"
maintainer:          "dongare.rahul@yahoo.com"
copyright:           "BSD"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/dongarerahul/haskell/words#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  words:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -dynamic

    dependencies:
    - words

tests:
  words-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - words
    - hspec
